server {
    listen 80;

    location /media/ {
        alias /mnt/;
        autoindex on;
    }

    location /playlist.m3u {
        proxy_pass http://vod:5000/playlist.m3u;
    }

    location /epg.xml {
        proxy_pass http://vod:5000/epg.xml;
    }

    location /api {
        proxy_pass http://vod:5000/api;
    }

    location / {
        proxy_pass http://vod:5000/;
    }
}
