# 👇 THIS PART MUST BE AT TOP LEVEL (http context)
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=vod_cache:10m max_size=20g inactive=24h use_temp_path=off;


server {

    listen 80;

    location /media/ {
        alias /mnt/;
        autoindex on;
    }
    # AUTH CHECK (token validation)
    location = /auth_token {
        internal;
        proxy_pass http://vod:5000/validate_token;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
    }


    location /playlist.m3u {
        proxy_pass http://vod:5000/playlist.m3u;
    }

    location /epg.xml {
        proxy_pass http://vod:5000/epg.xml;
    }

    location /api {
        proxy_pass http://vod:5000/api;
    }
    
    # STREAM
    location /stream/ {

        proxy_pass https://alist.chnjms.easypanel.host/d/;

        # 🔥 RANGE SUPPORT
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;

        # ⚡ CACHE
        proxy_cache vod_cache;
        proxy_cache_valid 200 206 24h;
        proxy_cache_lock on;

        # ⚡ BUFFERING
        proxy_buffering on;
        proxy_buffers 16 1m;
        proxy_buffer_size 1m;

        # ⚡ PERFORMANCE
        sendfile on;
        tcp_nopush on;

        # headers
        add_header X-Cache $upstream_cache_status;
        add_header Accept-Ranges bytes;
    }

    # APP
    location / {
        proxy_pass http://vod:5000;
    }
}
